### ISSUE TITLE
Conflitto di build su weka

### ISSUE THREAD

**Issue by innuendonh** [UmbertoAzadi/OUTLINE#2]
La dipendenza
```
		<dependency>
			<groupId>nz.ac.waikato.cms.weka</groupId>
			<artifactId>LibSVM</artifactId>
			<version>1.0.10</version>
		</dependency>
```

crea un conflitto di dipendenze con il resto del POM, perché cerca `weka-dev`, mentre viene usato `weka-stable` qui.
Per risolvere sarebbe necessario trovare una versione diversa di LibSVM oppure bloccare esplicitamente la dipendenza da `weka-dev`

**Comment by uazadi** [comment]
Dato che tra le dipendenze di LibSVM c'è già una versione di weka (weka-dev : 3.9.1) utilizzo quest'ultima al posto di weka-stable precedentemente scelta. Questo poiché weka-dev risulta essere la dipendenza più utilizzata guardando [https://mvnrepository.com/artifact/nz.ac.waikato.cms.weka](https://mvnrepository.com/artifact/nz.ac.waikato.cms.weka).
